### ISSUE TITLE
Release 6.1.0

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy.Analyzers#19]
- [x] Address all coding and style violations detected during a *Release* build (send a regular pull request which must be merged before continuing)
- [x] ensure completeness of draft [release notes](https://github.com/FakeItEasy/FakeItEasy.Analyzers/releases), including non-owner contributors, if any (move release notes forward from any pre-releases to the current release)
- [x] ensure that the analyzer still works with the versions of Visual Studio listed in the docs
   @blairconrad checked on VS2019 as indicated in the comments below
- [x] run `tools\prepare_release.cmd next x.y.z vNext` to:
    - change "vNext" names to appropriate x.y.z version for the next GitHub Release, milestone, and release checklist (this issue)
    - create a new draft GitHub Release, milestone, and release checklist
- [x] tag master with the new version number and push to upstream. This will cause the build server to
    - push the nupkgs to [nuget.org](https://www.nuget.org/profiles/FakeItEasy),
    - attach all nupkgs from the tagged build to the GitHub Release,
    - add a comment to each issue and pull request in the release, saying it was published in this release
- [x] wait for NuGet package validation
- [x] de-list pre-release NuGet packages if present
- [x] publish the GitHub release
- [x] tweet, mentioning contributors, and post link as comment here for easy retweeting ;-)
- [x] post tweet in [Gitter](https://gitter.im/FakeItEasy/FakeItEasy)
- [x] add a note in each issue that has a significant contribution from a community member, thanking the contributor
- [ ] close this issue
- [ ] if this is **not** a pre-release, close the [milestone](https://github.com/FakeItEasy/FakeItEasy.Analyzers/milestones?state=open) for this release

**Comment by blairconrad** [comment]
I was thinking we should release soon.
I was going down the checklist and got to

> ensure that the analyzer still works with the versions of Visual Studio listed in the docs

I don't have a VS 2017, but I did try on 2019 Version 16.8.3:
![image](https://user-images.githubusercontent.com/3275797/111245349-deaa4e80-85da-11eb-9d27-22668e459412.png)

Close enough? I can't think why it would've stopped working on VS 2017.
Should we update the docs to only promise VS 2019+?

**Comment by thomaslevesque** [comment]
> Close enough? I can't think why it would've stopped working on VS 2017.
> Should we update the docs to only promise VS 2019+?

I think it's close enough. It should still work in VS2017, since it's not actually related to Visual Studio (it also works if you build from the command line).

**Comment by blairconrad** [comment]
Shall we release then, @thomaslevesque ? 6.1.0?

**Comment by thomaslevesque** [comment]
> Shall we release then, @thomaslevesque ?

Yes, let's go!

> 6.1.0?

Sounds good to me

**Comment by blairconrad** [comment]
```
Get FakeItEasy.Analyzers 6.1.0!

New:
* warn of improper usage of An-based argument constraints introduced in FakeItEasy 7.0.0.
* specify developmentDependency=true in packages

https://github.com/FakeItEasy/FakeItEasy.Analyzers/releases/6.1.0
```
