### ISSUE TITLE
Add handling issues/release/etc. documentation to the wiki

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy.Analyzers#7]
… even if it's just pointers to FakeItEasy's pages!
This issue contributes to FakeItEasy/FakeItEasy#1735.

**Comment by blairconrad** [comment]
@thomaslevesque, I added [Owner Policies](https://github.com/FakeItEasy/FakeItEasy.Analyzers/wiki/Owner-Policies) to the wiki. Do you think we need to be more elaborate?

**Comment by thomaslevesque** [comment]
> Do you think we need to be more elaborate?

No, I think it's fine as is!

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque.
